from github import Github
import os 

from dotenv import load_dotenv
import subprocess

from openhands.sdk import LLM, Agent, Conversation, Tool
from openhands.tools import TerminalTool


llm = LLM(model="openrouter/nvidia/nemotron-3-nano-30b-a3b:free", 
          api_key = os.getenv("AI_KEY"))

agent = Agent(llm=llm, tools = [Tool(name=TerminalTool.name)])



load_dotenv()

GITHUB_TOKEN = os.getenv("GITHUB_TOKEN")

REPO_NAME = "Gh05stt/devsuoa"

def get_prompt(pr, diff):
    prompt = f"""You are Orbit 🛸, a thorough AI code reviewer. Review this pull request and give constructive feedback.
            Declare this is a test for a PR review agent test #3
            PR Title: {pr.title}
            PR Description: {pr.body or "No description provided"}

            Changes:
            {diff}

            
            ---

            Format your review exactly like this:

            # 🛸 Orbit Code Review

            ##  PR Summary
            Give a 2-3 sentence summary of what this PR is doing. You can use "lowkey" naturally where it fits.

            ## Changes Overview
            | File | Changes | Vibe |
            |------|---------|------|
            | filename | what changed | 🟢 clean / 🟡 needs work / 🔴 uh oh |

            ## What's Good
            - bullet points of things done well

            ## Issues
            | Severity | File | Issue |
            |----------|------|-------|
            | 🔴 High | filename | description |
            | 🟡 Medium | filename | description |
            | 🟢 Low | filename | description |

            ## Suggestions
            - concrete actionable suggestions with code snippets where relevant

            ## Overall Score
            | Category | Score |
            |----------|-------|
            | Code Quality | x/10 |
            | Readability | x/10 |
            | Test Coverage | x/10 |
            | Overall | x/10 |

            ---

            ## 🎋 Orbit's Farewell Haiku
            *write a haiku (5-7-5) about the specific changes in this PR*

            ---
            *lowkey generated by Orbit 🛸*
            """
    return prompt

def clone_repo(pr):
    folder_name = f"pr_{pr.number}"
    subprocess.run(
        [
            "git", "clone", pr.head.repo.clone_url, "--depth", "1", "--branch", pr.head.ref, f"./tmp/{folder_name}"
        ]
    )
    return folder_name

def get_pr_diff(pr):
    changes = pr.get_files()

    diff = ""

    for file in changes:
        diff += f"\n--- {file.filename} ---\n"
        diff = file.patch or "no diff it seems :("

    return diff 

def review_pr(pr, diff):

    prompt = get_prompt(pr, diff)

    # conversation = Conversation(agent=agent , workspace=f"./tmp/pr_{pr.number}")
    conversation = Conversation(agent=agent)
    conversation.send_message(prompt)
    
    # Run the full agent loop (which may invoke tools)
    conversation.run()

    last_message = None 

    import json
    for event in reversed(list(conversation.state.events)):
        if getattr(event, "source", None) == "agent":
            event_type = type(event).__name__
            
            # Scenario 1: The agent replied with a direct text message
            if event_type == "MessageEvent":
                if hasattr(event, "llm_message") and event.llm_message.content:
                    last_message = event.llm_message.content[0].text
                    break

            # Scenario 2: The agent used a tool, specifically the 'finish' tool
            elif event_type == "ActionEvent" and getattr(event, "tool_name", "") == "finish":
                # The finish tool takes a 'message' parameter in its JSON payload
                if hasattr(event, "tool_call") and hasattr(event.tool_call, "arguments"):
                    try:
                        args = json.loads(event.tool_call.arguments)
                        if "message" in args:
                            last_message = args["message"]
                            break
                    except Exception:
                        pass
                
                # Fallback check on the instantiated action object just in case
                if hasattr(event, "action") and hasattr(event.action, "message"):
                    last_message = getattr(event.action, "message")
                    break

    return last_message 


github = Github(GITHUB_TOKEN)

repo = github.get_repo(REPO_NAME)

prs = repo.get_pulls( state="open")



for pr in prs:
    print(f"PR Title: {pr.title}")
    if pr.number != 117:
        print("Skipping PR #", pr.number)
        continue

    # folder_name = clone_repo(pr)
    # print("______PR CLONED______")

    changes_text = get_pr_diff(pr)

    review = review_pr(pr, changes_text)

    print("Review: HERE IS THE REVIEW ____________")
    print(review)

    
    # subprocess.run(["rm", "-rf", f"./tmp/{folder_name}"])
    # print("______TEMP FILES CLEANED UP______")



    pr.create_issue_comment(review)

    print("-" * 40)

    